# Generated by Django 6.0.4 on 2026-04-21 10:25

from django.db import migrations, models

import reservations.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_password_auth"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reservation",
            new_name="reservation_resourc_cf30eb_idx",
            old_name="reservatio_resource_begin_idx",
        ),
        migrations.RenameIndex(
            model_name="resource",
            new_name="reservation_unit_id_6e6a1e_idx",
            old_name="reservatio_resource_unit_id_idx",
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.JSONField(blank=True, default=reservations.models.empty_localized_text),
        ),
        migrations.AlterField(
            model_name="resource",
            name="reservation_instructions",
            field=models.JSONField(blank=True, default=reservations.models.empty_localized_text),
        ),
        migrations.AlterField(
            model_name="unit",
            name="address",
            field=models.JSONField(blank=True, default=reservations.models.empty_localized_text),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["user", "begin"], name="reservation_user_id_ce3ead_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["state"], name="reservation_state_f6f01b_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["requires_approval"], name="reservation_require_1fca86_idx"),
        ),
    ]
